import gif_pygame

SAND_IMAGE = gif_pygame.load('images/sand.gif')
gif_pygame.transform.scale(SAND_IMAGE, (100, 100))
TILE_IMAGE = gif_pygame.load('images/tile.gif')
gif_pygame.transform.scale(TILE_IMAGE, (100, 100))
WALL_IMAGE = gif_pygame.load('images/wall.gif')
gif_pygame.transform.scale(WALL_IMAGE, (100, 100))
PIPE1_IMAGE = gif_pygame.load('images/u1.gif')
gif_pygame.transform.scale(PIPE1_IMAGE, (100, 100))
PIPE2_IMAGE = gif_pygame.load('images/u2.gif')
gif_pygame.transform.scale(PIPE2_IMAGE, (100, 100))
PIPE3_IMAGE = gif_pygame.load('images/u3.gif')
gif_pygame.transform.scale(PIPE3_IMAGE, (100, 100))
DOOR_IMAGE = gif_pygame.load('images/door.gif')
gif_pygame.transform.scale(DOOR_IMAGE, (100, 100))
OPENED_DOOR_IMAGE = gif_pygame.load('images/door.gif')
gif_pygame.transform.scale(OPENED_DOOR_IMAGE, (100, 100))
gif_pygame.transform.rotate(OPENED_DOOR_IMAGE, 90)
WALL2_IMAGE = gif_pygame.load('images/wall2.gif')
gif_pygame.transform.scale(WALL2_IMAGE, (100, 100))
WALL3_IMAGE = gif_pygame.load('images/wall3.gif')
gif_pygame.transform.scale(WALL3_IMAGE, (100, 100))
WALL4_IMAGE = gif_pygame.load('images/wall4.gif')
gif_pygame.transform.scale(WALL4_IMAGE, (100, 100))
TERMINAL_IMAGE = gif_pygame.load('images/terminal.gif')
gif_pygame.transform.scale(TERMINAL_IMAGE, (100, 100))
TERMINAL_SCREEN_IMAGE = gif_pygame.load('images/terminal_screen.gif')
gif_pygame.transform.scale(TERMINAL_SCREEN_IMAGE, (900, 900))
WEB1_IMAGE = gif_pygame.load('images/web1.gif')
gif_pygame.transform.scale(WEB1_IMAGE, (100, 100))
WEB2_IMAGE = gif_pygame.load('images/web2.gif')
gif_pygame.transform.scale(WEB2_IMAGE, (100, 100))


DOOR_2_IMAGE = gif_pygame.load('images/door.gif')
gif_pygame.transform.scale(DOOR_2_IMAGE, (100, 100))
gif_pygame.transform.rotate(DOOR_2_IMAGE, 90)
OPENED_DOOR_2_IMAGE = gif_pygame.load('images/door.gif')
gif_pygame.transform.scale(OPENED_DOOR_2_IMAGE, (100, 100))

PLAYER_OUTLINE_IMAGE = gif_pygame.load('images/player_outline.gif')
gif_pygame.transform.scale(PLAYER_OUTLINE_IMAGE, (100, 100))
PLAYER_DETAIL_IMAGE = gif_pygame.load('images/player_detail.gif')
gif_pygame.transform.scale(PLAYER_DETAIL_IMAGE, (100, 100))
PLAYER_FRONT_IMAGE = gif_pygame.load('images/player_front_image.gif')
gif_pygame.transform.scale(PLAYER_FRONT_IMAGE, (100, 100))
PLAYER_BACK_IMAGE = gif_pygame.load('images/player_back_image.gif')
gif_pygame.transform.scale(PLAYER_BACK_IMAGE, (100, 100))
PLAYER_LEFT_IMAGE = gif_pygame.load('images/player_left_image.gif')
gif_pygame.transform.scale(PLAYER_LEFT_IMAGE, (100, 100))
PLAYER_RIGHT_IMAGE = gif_pygame.load('images/player_right_image.gif')
gif_pygame.transform.scale(PLAYER_RIGHT_IMAGE, (100, 100))
PLAYER_FRONT_WALK_IMAGE = gif_pygame.load('images/player_front_walk_image.gif')
gif_pygame.transform.scale(PLAYER_FRONT_WALK_IMAGE, (100, 100))
PLAYER_BACK_WALK_IMAGE = gif_pygame.load('images/player_back_walk_image.gif')
gif_pygame.transform.scale(PLAYER_BACK_WALK_IMAGE, (100, 100))
PLAYER_LEFT_WALK_IMAGE = gif_pygame.load('images/player_left_walk_image.gif')
gif_pygame.transform.scale(PLAYER_LEFT_WALK_IMAGE, (100, 100))
PLAYER_RIGHT_WALK_IMAGE = gif_pygame.load('images/player_right_walk_image.gif')
gif_pygame.transform.scale(PLAYER_RIGHT_WALK_IMAGE, (100, 100))

VIGNETTE1_IMAGE = gif_pygame.load('images/vignette1.gif')
gif_pygame.transform.scale(VIGNETTE1_IMAGE, (900, 900))
VIGNETTE2_IMAGE = gif_pygame.load('images/vignette2.gif')
gif_pygame.transform.scale(VIGNETTE2_IMAGE, (900, 900))

STOP_IMAGE = gif_pygame.load('images/stop.gif')
gif_pygame.transform.scale(STOP_IMAGE, (100, 100))
BOTTLE_IMAGE = gif_pygame.load('images/bottle.gif')
gif_pygame.transform.scale(BOTTLE_IMAGE, (100, 100))
KEY_IMAGE = gif_pygame.load('images/key2.gif')
gif_pygame.transform.scale(KEY_IMAGE, (100, 100))
FLASHLIGHT_IMAGE = gif_pygame.load('images/flashlight.gif')
gif_pygame.transform.scale(FLASHLIGHT_IMAGE, (100, 100))

HOARDING_BUG_IMAGE = gif_pygame.load('images/hoarding_bug_image.gif')
gif_pygame.transform.scale(HOARDING_BUG_IMAGE, (100, 100))
HOARDING_BUG_WALK_IMAGE = gif_pygame.load('images/hoarding_bug_walk_image.gif')
gif_pygame.transform.scale(HOARDING_BUG_WALK_IMAGE, (100, 100))
BRACKEN_IMAGE = gif_pygame.load('images/bracken_image.gif')
gif_pygame.transform.scale(BRACKEN_IMAGE, (100, 100))
BRACKEN_WALK_IMAGE = gif_pygame.load('images/bracken_walk_image.gif')
gif_pygame.transform.scale(BRACKEN_WALK_IMAGE, (100, 100))
COIL_HEAD_IMAGE = gif_pygame.load('images/coil_head_image.gif')
gif_pygame.transform.scale(COIL_HEAD_IMAGE, (100, 100))
JESTER_IMAGE = gif_pygame.load('images/jester.gif')
gif_pygame.transform.scale(JESTER_IMAGE, (100, 100))
JESTER_DOING_IMAGE = gif_pygame.load('images/jester_doing.gif')
gif_pygame.transform.scale(JESTER_DOING_IMAGE, (100, 100))
JESTER_WALK_IMAGE = gif_pygame.load('images/jester_walk.gif')
gif_pygame.transform.scale(JESTER_WALK_IMAGE, (100, 100))
JESTER_OPENED_IMAGE = gif_pygame.load('images/jester_opened.gif')
gif_pygame.transform.scale(JESTER_OPENED_IMAGE, (100, 100))
JESTER_OPENED_WALK_IMAGE = gif_pygame.load('images/jester_opened_walk.gif')
gif_pygame.transform.scale(JESTER_OPENED_WALK_IMAGE, (100, 100))