import gif_pygame
import pyautogui

CONFIG = {
    'TILE_SIZE': 100
}

SAND_IMAGE = gif_pygame.load('images/tile/sand.gif')
gif_pygame.transform.scale(SAND_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
TILE_IMAGE = gif_pygame.load('images/tile/tile.gif')
gif_pygame.transform.scale(TILE_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
WALL_IMAGE = gif_pygame.load('images/tile/wall.gif')
gif_pygame.transform.scale(WALL_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
PIPE1_IMAGE = gif_pygame.load('images/tile/u1.gif')
gif_pygame.transform.scale(PIPE1_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
PIPE2_IMAGE = gif_pygame.load('images/tile/u2.gif')
gif_pygame.transform.scale(PIPE2_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
PIPE3_IMAGE = gif_pygame.load('images/tile/u3.gif')
gif_pygame.transform.scale(PIPE3_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
DOOR_IMAGE = gif_pygame.load('images/tile/door.gif')
gif_pygame.transform.scale(DOOR_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
OPENED_DOOR_IMAGE = gif_pygame.load('images/tile/door.gif')
gif_pygame.transform.scale(OPENED_DOOR_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
gif_pygame.transform.rotate(OPENED_DOOR_IMAGE, 90)
WALL2_IMAGE = gif_pygame.load('images/tile/wall2.gif')
gif_pygame.transform.scale(WALL2_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
WALL3_IMAGE = gif_pygame.load('images/tile/wall3.gif')
gif_pygame.transform.scale(WALL3_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
WALL4_IMAGE = gif_pygame.load('images/tile/wall4.gif')
gif_pygame.transform.scale(WALL4_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
TERMINAL_IMAGE = gif_pygame.load('images/tile/terminal.gif')
gif_pygame.transform.scale(TERMINAL_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
TERMINAL_SCREEN_IMAGE = gif_pygame.load('images/overlay/terminal_screen.gif')
gif_pygame.transform.scale(TERMINAL_SCREEN_IMAGE, (900, 900))
WEB1_IMAGE = gif_pygame.load('images/tile/web1.gif')
gif_pygame.transform.scale(WEB1_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
WEB2_IMAGE = gif_pygame.load('images/tile/web2.gif')
gif_pygame.transform.scale(WEB2_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
DOOR_2_IMAGE = gif_pygame.load('images/tile/door.gif')
gif_pygame.transform.scale(DOOR_2_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
gif_pygame.transform.rotate(DOOR_2_IMAGE, 90)
OPENED_DOOR_2_IMAGE = gif_pygame.load('images/tile/door.gif')
gif_pygame.transform.scale(OPENED_DOOR_2_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
CHARGER_IMAGE = gif_pygame.load('images/tile/charger.gif')
gif_pygame.transform.scale(CHARGER_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
TILE_2_IMAGE = gif_pygame.load('images/tile/tile2.gif')
gif_pygame.transform.scale(TILE_2_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
COMPANY_TILE_1_IMAGE = gif_pygame.load('images/tile/company_tile1.gif')
gif_pygame.transform.scale(COMPANY_TILE_1_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
COMPANY_TILE_2_IMAGE = gif_pygame.load('images/tile/company_tile2.gif')
gif_pygame.transform.scale(COMPANY_TILE_2_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))

DELIVERY_IMAGE = gif_pygame.load('images/delivery/delivery.gif')
gif_pygame.transform.scale(DELIVERY_IMAGE, (3 * CONFIG['TILE_SIZE'], 3 * CONFIG['TILE_SIZE']))
DELIVERY_FIRE_IMAGE = gif_pygame.load('images/delivery/delivery_fire.gif')
gif_pygame.transform.scale(DELIVERY_FIRE_IMAGE, (3 * CONFIG['TILE_SIZE'], 3 * CONFIG['TILE_SIZE']))

PLAYER_OUTLINE_IMAGE = gif_pygame.load('images/player/player_outline.gif')
gif_pygame.transform.scale(PLAYER_OUTLINE_IMAGE, (100, 100))
PLAYER_DETAIL_IMAGE = gif_pygame.load('images/player/player_detail.gif')
gif_pygame.transform.scale(PLAYER_DETAIL_IMAGE, (100, 100))
PLAYER_FRONT_IMAGE = gif_pygame.load('images/player/player_front_image.gif')
gif_pygame.transform.scale(PLAYER_FRONT_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
PLAYER_BACK_IMAGE = gif_pygame.load('images/player/player_back_image.gif')
gif_pygame.transform.scale(PLAYER_BACK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
PLAYER_LEFT_IMAGE = gif_pygame.load('images/player/player_left_image.gif')
gif_pygame.transform.scale(PLAYER_LEFT_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
PLAYER_RIGHT_IMAGE = gif_pygame.load('images/player/player_right_image.gif')
gif_pygame.transform.scale(PLAYER_RIGHT_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
PLAYER_FRONT_WALK_IMAGE = gif_pygame.load('images/player/player_front_walk_image.gif')
gif_pygame.transform.scale(PLAYER_FRONT_WALK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
PLAYER_BACK_WALK_IMAGE = gif_pygame.load('images/player/player_back_walk_image.gif')
gif_pygame.transform.scale(PLAYER_BACK_WALK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
PLAYER_LEFT_WALK_IMAGE = gif_pygame.load('images/player/player_left_walk_image.gif')
gif_pygame.transform.scale(PLAYER_LEFT_WALK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
PLAYER_RIGHT_WALK_IMAGE = gif_pygame.load('images/player/player_right_walk_image.gif')
gif_pygame.transform.scale(PLAYER_RIGHT_WALK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))

VIGNETTE1_IMAGE = gif_pygame.load('images/overlay/vignette1.gif')
gif_pygame.transform.scale(VIGNETTE1_IMAGE, (pyautogui.size()[1], pyautogui.size()[1]))
VIGNETTE2_IMAGE = gif_pygame.load('images/overlay/vignette2.gif')
gif_pygame.transform.scale(VIGNETTE2_IMAGE, (pyautogui.size()[1], pyautogui.size()[1]))

STOP_IMAGE = gif_pygame.load('images/item/stop.gif')
gif_pygame.transform.scale(STOP_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
BOTTLE_IMAGE = gif_pygame.load('images/item/bottle.gif')
gif_pygame.transform.scale(BOTTLE_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
KEY_IMAGE = gif_pygame.load('images/item/key2.gif')
gif_pygame.transform.scale(KEY_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
FLASHLIGHT_IMAGE = gif_pygame.load('images/item/flashlight.gif')
gif_pygame.transform.scale(FLASHLIGHT_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
SHOVEL_IMAGE = gif_pygame.load('images/item/shovel.gif')
gif_pygame.transform.scale(SHOVEL_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
AIRHORN_IMAGE = gif_pygame.load('images/item/airhorn.gif')
gif_pygame.transform.scale(AIRHORN_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
BIGBOLT_IMAGE = gif_pygame.load('images/item/bigbolt.gif')
gif_pygame.transform.scale(BIGBOLT_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
CLOWNHORN_IMAGE = gif_pygame.load('images/item/clownhorn.gif')
gif_pygame.transform.scale(CLOWNHORN_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
COFFEE_MUG_IMAGE = gif_pygame.load('images/item/coffee mug.gif')
gif_pygame.transform.scale(COFFEE_MUG_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
COMEDY_IMAGE = gif_pygame.load('images/item/comedy.gif')
gif_pygame.transform.scale(COMEDY_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
FLASK_IMAGE = gif_pygame.load('images/item/flask.gif')
gif_pygame.transform.scale(FLASK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
GIFTBOX_IMAGE = gif_pygame.load('images/item/giftbox.gif')
gif_pygame.transform.scale(GIFTBOX_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
WHOOPIE_CUSHION_IMAGE = gif_pygame.load('images/item/whoopie_cushion.gif')
gif_pygame.transform.scale(WHOOPIE_CUSHION_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
CUBE_IMAGE = gif_pygame.load('images/item/cube.gif')
gif_pygame.transform.scale(CUBE_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
TOOTHPASTE_IMAGE = gif_pygame.load('images/item/toothpaste.gif')
gif_pygame.transform.scale(TOOTHPASTE_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
KETTLE_IMAGE = gif_pygame.load('images/item/kettle.gif')
gif_pygame.transform.scale(KETTLE_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
DUCK_IMAGE = gif_pygame.load('images/item/duck.gif')
gif_pygame.transform.scale(DUCK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
RING_IMAGE = gif_pygame.load('images/item/ring.gif')
gif_pygame.transform.scale(RING_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
SODA_IMAGE = gif_pygame.load('images/item/soda.gif')
gif_pygame.transform.scale(SODA_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
PLASTIC_FISH_IMAGE = gif_pygame.load('images/item/plastic_fish.gif')
gif_pygame.transform.scale(PLASTIC_FISH_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
MEDICINE_IMAGE = gif_pygame.load('images/item/medicine.gif')
gif_pygame.transform.scale(MEDICINE_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
HOMESICK_IMAGE = gif_pygame.load('images/item/homesick.gif')
gif_pygame.transform.scale(HOMESICK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
READING_GLASSES_IMAGE = gif_pygame.load('images/item/reading_glasses.gif')
gif_pygame.transform.scale(READING_GLASSES_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
BALL_SEVEN_IMAGE = gif_pygame.load('images/item/ball_seven.gif')
gif_pygame.transform.scale(BALL_SEVEN_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
HAIR_DRYER_IMAGE = gif_pygame.load('images/item/hair_dryer.gif')
gif_pygame.transform.scale(HAIR_DRYER_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
HAIR_COMB_IMAGE = gif_pygame.load('images/item/hair_comb.gif')
gif_pygame.transform.scale(HAIR_COMB_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
GOLDEN_CUP_IMAGE = gif_pygame.load('images/item/golden_cup.gif')
gif_pygame.transform.scale(GOLDEN_CUP_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
EGG_BEATER_IMAGE = gif_pygame.load('images/item/egg_beater.gif')
gif_pygame.transform.scale(EGG_BEATER_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
BRASS_BELL_IMAGE = gif_pygame.load('images/item/brass_bell.gif')
gif_pygame.transform.scale(BRASS_BELL_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))

HOARDING_BUG_IMAGE = gif_pygame.load('images/monster/hoarding_bug/hoarding_bug_image.gif')
gif_pygame.transform.scale(HOARDING_BUG_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
HOARDING_BUG_WALK_IMAGE = gif_pygame.load('images/monster/hoarding_bug/hoarding_bug_walk_image.gif')
gif_pygame.transform.scale(HOARDING_BUG_WALK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))

BRACKEN_IMAGE = gif_pygame.load('images/monster/bracken/bracken_image.gif')
gif_pygame.transform.scale(BRACKEN_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
BRACKEN_WALK_IMAGE = gif_pygame.load('images/monster/bracken/bracken_walk_image.gif')
gif_pygame.transform.scale(BRACKEN_WALK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))

COIL_HEAD_IMAGE = gif_pygame.load('images/monster/coil_head/coil_head_image.gif')
gif_pygame.transform.scale(COIL_HEAD_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))

JESTER_IMAGE = gif_pygame.load('images/monster/jester/jester.gif')
gif_pygame.transform.scale(JESTER_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
JESTER_DOING_IMAGE = gif_pygame.load('images/monster/jester/jester_doing.gif')
gif_pygame.transform.scale(JESTER_DOING_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
JESTER_WALK_IMAGE = gif_pygame.load('images/monster/jester/jester_walk.gif')
gif_pygame.transform.scale(JESTER_WALK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
JESTER_OPENED_IMAGE = gif_pygame.load('images/monster/jester/jester_opened.gif')
gif_pygame.transform.scale(JESTER_OPENED_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
JESTER_OPENED_WALK_IMAGE = gif_pygame.load('images/monster/jester/jester_opened_walk.gif')
gif_pygame.transform.scale(JESTER_OPENED_WALK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))

MINE_IMAGE = gif_pygame.load('images/monster/mine/mine.gif')
gif_pygame.transform.scale(MINE_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
MINE_FIRE_IMAGE = gif_pygame.load('images/monster/mine/fire.gif')
gif_pygame.transform.scale(MINE_FIRE_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))

TERROR_IMAGE = gif_pygame.load('images/monster/terror/terror.gif')
gif_pygame.transform.scale(TERROR_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))

GIRL_IMAGE = gif_pygame.load('images/monster/girl/girl.gif')
gif_pygame.transform.scale(GIRL_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
GIRL_WALK_IMAGE = gif_pygame.load('images/monster/girl/girl_walk.gif')
gif_pygame.transform.scale(GIRL_WALK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))

MASK_FRONT_IMAGE = gif_pygame.load('images/monster/mask/player_front_image.gif')
gif_pygame.transform.scale(MASK_FRONT_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
MASK_BACK_IMAGE = gif_pygame.load('images/monster/mask/player_back_image.gif')
gif_pygame.transform.scale(MASK_BACK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
MASK_LEFT_IMAGE = gif_pygame.load('images/monster/mask/player_left_image.gif')
gif_pygame.transform.scale(MASK_LEFT_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
MASK_RIGHT_IMAGE = gif_pygame.load('images/monster/mask/player_right_image.gif')
gif_pygame.transform.scale(MASK_RIGHT_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
MASK_FRONT_WALK_IMAGE = gif_pygame.load('images/monster/mask/player_front_walk_image.gif')
gif_pygame.transform.scale(MASK_FRONT_WALK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
MASK_BACK_WALK_IMAGE = gif_pygame.load('images/monster/mask/player_back_walk_image.gif')
gif_pygame.transform.scale(MASK_BACK_WALK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
MASK_LEFT_WALK_IMAGE = gif_pygame.load('images/monster/mask/player_left_walk_image.gif')
gif_pygame.transform.scale(MASK_LEFT_WALK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))
MASK_RIGHT_WALK_IMAGE = gif_pygame.load('images/monster/mask/player_right_walk_image.gif')
gif_pygame.transform.scale(MASK_RIGHT_WALK_IMAGE, (1 * CONFIG['TILE_SIZE'], 1 * CONFIG['TILE_SIZE']))

STARS_VIDEO = gif_pygame.load('images/stars.gif')
gif_pygame.transform.scale(STARS_VIDEO, (900, 900))